### PR TITLE
fix regression in construct-env.ts

### LINKED ISSUE #1036: strange behaviors with 1.2.0
These are different:

CMAKE_INCLUDE_PATH doesn't seem to be being set: https://github.com/pkgxdev/pantry/actions/runs/10776133971/job/29882224768 (1 example; a fix for another was explicit paths: https://github.com/pkgxdev/pantry/pull/7236/files

LD_LIBRARY_PATH (and path, weirdly) don't seem to include runtime deps with brewkit test? maybe? or the output is strange from brewkit is strange: https://github.com/pkgxdev/pantry/actions/runs/10820659200/job/30021167540. This should show php.net in PATH (though it clearly works on the command), and LD_LIBRARY_PATH doesn't seem to include gnu.org/gcc/libstdcxx. weirdly, laravel (#!/usr/bin/env php) works fine, but `php artisan` and `./artisan`, same bang-path, have GLIBCXX errors.

note that the second appears to be the same issue you saw in CI/CD with nodejs.

### PR DESCRIPTION
**Pull request by jhheider**
closes #1036

### CODE REVIEW

**Comment by mxcl** [comment]
I'm confused how this fixes things. If the assert was triggering before how were builds still continuing with a reduced env?

**Comment by jhheider** [comment]
the assertions weren't triggering except in maybe 1 build (maybe? or zero.) but were preventing things like postgres and node from working in the same env.

however, the _fix_ basically broke `cmake` detection on line 69 and autoconf detection on line 73, since those both use `Set.has()`, and we changed the format of the set members.

**Comment by mxcl** [comment]
cd failure https://github.com/pkgxdev/pkgx/actions/runs/10854509536/job/30125478243

**Comment by jhheider** [comment]
both `./pkgx gpg-agent --daemon` and `bash -c './pkgx gpg-agent --daemon'` work in docker. so. frustrating.

**Comment by jhheider** [comment]
even `echo 5 | cat | ./pkgx +sqlite3 gpg --import --batch --yes` works. so, this is another of the specie of "incomplete LD_LIBRARY_PATH", which isn't identified or fixed. i'll dig further.

**Comment by jhheider** [comment]
```shell
pkgx/pkgx $ ./pkgx +gnupg.org | grep LD_LIB | tr : '\n'  | grep readline
/root/.pkgx/gnu.org/readline/v8.2.13/lib
```

**Comment by mxcl** [comment]
yeah only fails for linux aarch64 and well, it's using the just built `pkgx` to execute `gpg` so suggests this fix isn't sufficient

**Comment by mxcl** [comment]
The draft release could just be released without linux aarch64 since like, it's the least interesting platform

**Comment by jhheider** [comment]
i can't prove it, but the only thing that changed for deps is the sync cache. so, db corruption, or an incomplete await, or something could have short data.

but deleting the deps in my pantry.db doesn't even affect my local invocation, so that's more mysterious. it's odd that `db.sql` is synchronous, but everything _looks like it should work_.

the fact that it's only messing up the LD_LIBRARY_PATH on linuxen is also concerning.

**Comment by jhheider** [comment]
you know, the runners aren't clearing ~/.cache/pkgx; maybe I update their script and see.

**Comment by jhheider** [comment]
that fixed it _immediately_. so it's cache corruption. fun. i bet `laravel` builds now.

**Comment by jhheider** [comment]
couldn't be that easy, i guess: https://github.com/pkgxdev/pantry/actions/runs/10820951092/job/30130754367?pr=7239

**Comment by mxcl** [comment]
If you can `ssh` in, what does `pkgx +php.net +gnu.org/gcc/libstdcxx` output?

**Comment by mxcl** [comment]
Maybe downgrade `pkgx` in the actions for now.

**Comment by jhheider** [comment]
> If you can `ssh` in, what does `pkgx +php.net +gnu.org/gcc/libstdcxx` output?

```shell
$ builder@f8b90684f45a:/$ pkgx +gnu.org/gcc/libstdcxx
 ✓  ~/.pkgx/gnu.org/mpc/v1.3.1
 ✓  ~/.pkgx/gnu.org/gmp/v6.3.0
 ✓  ~/.pkgx/gnu.org/mpfr/v4.2.1
 ✓  ~/.pkgx/gnu.org/gcc/libstdcxx/v14.2.0
 ✓  ~/.pkgx/gnu.org/binutils/v2.43.1
PATH="/home/builder/.pkgx/gnu.org/binutils/v2.43.1/bin${PATH:+:$PATH}"
CPATH="/home/builder/.pkgx/gnu.org/binutils/v2.43.1/include:/home/builder/.pkgx/gnu.org/gcc/libstdcxx/v14.2.0/include:/home/builder/.pkgx/gnu.org/mpc/v1.3.1/include:/home/builder/.pkgx/gnu.org/mpfr/v4.2.1/include:/home/builder/.pkgx/gnu.org/gmp/v6.3.0/include${CPATH:+:$CPATH}"
LIBRARY_PATH="/home/builder/.pkgx/gnu.org/binutils/v2.43.1/lib:/home/builder/.pkgx/gnu.org/gcc/libstdcxx/v14.2.0/lib:/home/builder/.pkgx/gnu.org/mpc/v1.3.1/lib:/home/builder/.pkgx/gnu.org/mpfr/v4.2.1/lib:/home/builder/.pkgx/gnu.org/gmp/v6.3.0/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
XDG_DATA_DIRS="/home/builder/.pkgx/gnu.org/binutils/v2.43.1/share:/home/builder/.pkgx/gnu.org/gcc/libstdcxx/v14.2.0/share:/home/builder/.pkgx/gnu.org/mpc/v1.3.1/share:/home/builder/.pkgx/gnu.org/mpfr/v4.2.1/share:/home/builder/.pkgx/gnu.org/gmp/v6.3.0/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
MANPATH="/home/builder/.pkgx/gnu.org/binutils/v2.43.1/share/man:${MANPATH}:/usr/share/man"
PKG_CONFIG_PATH="/home/builder/.pkgx/gnu.org/mpfr/v4.2.1/lib/pkgconfig:/home/builder/.pkgx/gnu.org/gmp/v6.3.0/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
LD_LIBRARY_PATH="/home/builder/.pkgx/gnu.org/binutils/v2.43.1/lib:/home/builder/.pkgx/gnu.org/gcc/libstdcxx/v14.2.0/lib:/home/builder/.pkgx/gnu.org/mpc/v1.3.1/lib:/home/builder/.pkgx/gnu.org/mpfr/v4.2.1/lib:/home/builder/.pkgx/gnu.org/gmp/v6.3.0/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
```

**Comment by jhheider** [comment]
> Maybe downgrade `pkgx` in the actions for now.

probably an ok move

**Comment by mxcl** [comment]
Seems to contain `/home/builder/.pkgx/gnu.org/gcc/libstdcxx/v14.2.0/lib` in the `LD_LIBRARY_PATH` setter.

**Comment by jhheider** [comment]
yup, and even reverting to 1.1.6 doesn't solve it: https://github.com/pkgxdev/pantry/actions/runs/10891688927/job/30223144500

something strange up with x86-64. maybe the lib isn't in the right place.

**Comment by jhheider** [comment]
nah, couldn't be that easy:
```shell
pkgx/work $ ls ~/.pkgx/gnu.org/gcc/libstdcxx/v14.2.0/lib/
gcc            libstdc++.so                libstdc++exp.la
libgcc_s.so    libstdc++.so.6              libstdc++fs.a
libgcc_s.so.1  libstdc++.so.6.0.33         libstdc++fs.la
libstdc++.a    libstdc++.so.6.0.33-gdb.py  libsupc++.a
libstdc++.la   libstdc++exp.a              libsupc++.la
```

**Comment by jhheider** [comment]
```
/root/.pkgx/gnu.org/gcc/libstdcxx/v14.2.0/lib/libstdc++.so.6.0.33:        ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, with debug_info, not stripped
```

**Comment by jhheider** [comment]
very mysterious.

**Pull request merged**
