### PR TITLE
Add support for .terraform-version file format for dev command

### LINKED ISSUE #831: Add support for .terraform-version in dev cli
`.terraform-version` is a file which contains the version of [terraform](https://github.com/hashicorp/terraform). This particular file is generally read by tools like [tfenv](https://github.com/tfutils/tfenv) to switch between different versions of terraform as we jump across directories using the `cd` command.

It would be great if `dev` command can support this `.terraform-version` file format and install appropriate versions of terraform

### PR DESCRIPTION
**Pull request by kishaningithub**
Fixes #831

### CODE REVIEW

**Review by mxcl — APPROVED** [review]

**Comment by mxcl** [comment]
Thank you @kishaningithub for your excellent feedback and now your contribution also.

**Comment by mxcl** [comment]
Will publish 1.0.5 by EoW

**Comment by kishaningithub** [comment]
By creating this PR i also learnt that deno can publish a self contained binary and can also cross compile. Previously i was of the opinion that only languages like golang can do something like that.

**Comment by mxcl** [comment]
run `deno task install` if you want `/usr/local/bin/pkgx` with this change in the meantime.

**Pull request merged**
